version: "3.8"

services:
  db_ingresso:
    container_name: db_api_dev
    image: postgres:13-alpine
    volumes:
      - postgres_api_wl_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - DJANGO_SETTINGS_MODULE=ingresso_express.settings
    env_file:
      - ./.env.dev
    ports:
      - "5435:5432"

  web_ingresso:
    container_name: api_wl_dev
    image: api_wl_dev_img
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db_api

    env_file:
      - ./.env.dev

volumes:
  postgres_api_wl: